name: Update Bookmarks

on:
  push:
    branches:
      - main

  schedule:
    # every 60 minutes - https://crontab.guru/#*_0_*_*_*
    - cron:  '* 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}

    steps:
      - uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          cache: "pip"
          python-version: "3.9"

      - name: Install our project requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Remove Duplicate Bookmarks
        run: |
          python main.py remove_dupes

      - name: Fix Bookmark Tags
        run: |
          python main.py fix_tags

      # - name: Fix Titlecase
      #   run: |
      #     python main.py fix_titlecase
